import type { Transaction } from '../types';

export const seedTransactions: Transaction[] = [
  // --- CURRENT MONTH: April 2026 ---
  {
    id: 'seed-sal-apr26',
    amount: 85000,
    currency: 'INR',
    vendor: 'TechCorp Solutions Pvt Ltd',
    date: '2026-04-01',
    category: 'salary',
    description: 'Monthly salary credit — April 2026',
    isTaxDeductible: false,
    taxType: 'TDS',
    taxAmount: 7083,
    confidence: 0.97,
    documentType: 'salary_slip',
    source: 'upload',
    rawOcrText: 'TechCorp Solutions Pvt Ltd\nSalary Slip April 2026\nGross: 85,000\nTDS: 7,083\nNet: 77,917',
    aiReasoning: 'Identified as salary credit from employer TechCorp Solutions. TDS of ₹7,083 deducted at source under Section 192. This represents ~30% effective tax bracket withholding on monthly income.',
    monthYear: '2026-04',
    createdAt: '2026-04-01T09:00:00Z',
    humanReviewed: true,
  },
  {
    id: 'seed-swiggy-apr1',
    amount: 456,
    currency: 'INR',
    vendor: 'Swiggy',
    date: '2026-04-03',
    category: 'food',
    description: 'Swiggy order — Biryani + sides',
    isTaxDeductible: false,
    taxType: 'GST',
    taxAmount: 23,
    confidence: 0.94,
    documentType: 'upi_screenshot',
    source: 'camera',
    rawOcrText: 'Swiggy\nOrder #SW9283746\nBiryani combo ₹380\nDelivery ₹49\nGST ₹23\nTotal ₹456',
    aiReasoning: 'Food delivery order from Swiggy. Categorized as food/dining. GST of 5% applied on restaurant services. Not deductible as personal food expense.',
    monthYear: '2026-04',
    createdAt: '2026-04-03T13:30:00Z',
    humanReviewed: false,
  },
  {
    id: 'seed-ola-apr1',
    amount: 342,
    currency: 'INR',
    vendor: 'Ola',
    date: '2026-04-04',
    category: 'transport',
    description: 'Ola ride — Koramangala to Whitefield',
    isTaxDeductible: false,
    taxType: 'GST',
    taxAmount: 17,
    confidence: 0.92,
    documentType: 'upi_screenshot',
    source: 'camera',
    rawOcrText: 'Ola Cabs\nTrip: Koramangala → Whitefield\nFare ₹310\nConvenience fee ₹15\nGST ₹17\nTotal ₹342',
    aiReasoning: 'Ride-hailing service from Ola. Route indicates personal commute. GST at 5% on transportation. Not deductible unless for business travel with documentation.',
    monthYear: '2026-04',
    createdAt: '2026-04-04T08:45:00Z',
    humanReviewed: false,
  },
  {
    id: 'seed-bigbasket-apr',
    amount: 2187,
    currency: 'INR',
    vendor: 'BigBasket',
    date: '2026-04-06',
    category: 'food',
    description: 'BigBasket — weekly groceries',
    isTaxDeductible: false,
    taxType: 'GST',
    taxAmount: 87,
    confidence: 0.91,
    documentType: 'receipt',
    source: 'upload',
    rawOcrText: 'BigBasket\nOrder #BB2026040623\nVegetables ₹450\nDairy ₹320\nFruits ₹280\nStaples ₹890\nSnacks ₹247\nTotal ₹2,187',
    aiReasoning: 'Grocery order from BigBasket. Mixed GST rates: 0% on fresh vegetables and fruits, 5% on dairy, 12% on packaged staples, 18% on snacks. Aggregate GST ₹87. Personal household expense — not deductible.',
    monthYear: '2026-04',
    createdAt: '2026-04-06T10:00:00Z',
    humanReviewed: false,
  },
  {
    id: 'seed-airtel-apr',
    amount: 2400,
    currency: 'INR',
    vendor: 'Airtel',
    date: '2026-04-07',
    category: 'utilities',
    description: 'Airtel broadband — monthly plan',
    isTaxDeductible: true,
    taxType: 'GST',
    taxAmount: 366,
    confidence: 0.89,
    documentType: 'invoice',
    source: 'gmail',
    rawOcrText: 'Bharti Airtel Ltd\nBroadband Bill April 2026\nPlan: 200 Mbps Unlimited\nBase ₹2,034\nGST 18% ₹366\nTotal ₹2,400',
    aiReasoning: 'Internet broadband bill from Airtel. GST at 18% on telecom services. Potentially deductible under Section 80C if used for work-from-home or freelance business. Marked deductible as user profile indicates tech professional with WFH setup.',
    monthYear: '2026-04',
    createdAt: '2026-04-07T06:00:00Z',
    humanReviewed: false,
  },
  {
    id: 'seed-aws-apr',
    amount: 1299,
    currency: 'INR',
    vendor: 'Amazon Web Services',
    date: '2026-04-10',
    category: 'business',
    description: 'AWS — monthly cloud hosting',
    isTaxDeductible: true,
    taxType: 'GST',
    taxAmount: 198,
    confidence: 0.95,
    documentType: 'invoice',
    source: 'gmail',
    rawOcrText: 'Amazon Web Services Inc.\nInvoice April 2026\nEC2 ₹650\nS3 ₹180\nRDS ₹271\nGST 18% ₹198\nTotal ₹1,299',
    aiReasoning: 'Cloud infrastructure bill from AWS. Business expense for hosting side projects/freelance work. GST at 18% on IT services. Fully deductible as professional business expense under Section 37(1) for self-employed income.',
    monthYear: '2026-04',
    createdAt: '2026-04-10T04:00:00Z',
    humanReviewed: true,
  },
  {
    id: 'seed-zomato-apr',
    amount: 623,
    currency: 'INR',
    vendor: 'Zomato',
    date: '2026-04-12',
    category: 'food',
    description: 'Zomato order — Pizza + dessert',
    isTaxDeductible: false,
    taxType: 'GST',
    taxAmount: 31,
    confidence: 0.93,
    documentType: 'upi_screenshot',
    source: 'camera',
    rawOcrText: 'Zomato\nOrder #ZMT82934\nPizza Margherita ₹399\nChoco Lava Cake ₹149\nDelivery ₹44\nGST ₹31\nTotal ₹623',
    aiReasoning: 'Food delivery order from Zomato. Categorized as food/dining. GST of 5% applied on restaurant services. Personal expense — not deductible.',
    monthYear: '2026-04',
    createdAt: '2026-04-12T20:15:00Z',
    humanReviewed: false,
  },
  {
    id: 'seed-rent-apr',
    amount: 12500,
    currency: 'INR',
    vendor: 'Landlord — Ashok Kumar',
    date: '2026-04-05',
    category: 'rent',
    description: 'Monthly rent — 2BHK Koramangala',
    isTaxDeductible: false,
    taxType: 'none',
    taxAmount: null,
    confidence: 0.88,
    documentType: 'upi_screenshot',
    source: 'camera',
    rawOcrText: 'UPI Payment\nTo: Ashok Kumar\nAmount: ₹12,500\nNote: April rent',
    aiReasoning: 'Rent payment via UPI to landlord. No GST applicable on residential rent below ₹20,000/month. Could be deductible under Section 10(13A) HRA exemption if salary has HRA component — requires employer documentation to confirm.',
    monthYear: '2026-04',
    createdAt: '2026-04-05T09:00:00Z',
    humanReviewed: false,
  },
  // --- PREVIOUS MONTH: March 2026 ---
  {
    id: 'seed-sal-mar26',
    amount: 85000,
    currency: 'INR',
    vendor: 'TechCorp Solutions Pvt Ltd',
    date: '2026-03-01',
    category: 'salary',
    description: 'Monthly salary credit — March 2026',
    isTaxDeductible: false,
    taxType: 'TDS',
    taxAmount: 7083,
    confidence: 0.97,
    documentType: 'salary_slip',
    source: 'upload',
    rawOcrText: 'TechCorp Solutions Pvt Ltd\nSalary Slip March 2026\nGross: 85,000\nTDS: 7,083\nNet: 77,917',
    aiReasoning: 'Monthly salary from TechCorp Solutions. TDS deducted at source per Section 192. Consistent with previous month pattern.',
    monthYear: '2026-03',
    createdAt: '2026-03-01T09:00:00Z',
    humanReviewed: true,
  },
  {
    id: 'seed-jetbrains-mar',
    amount: 599,
    currency: 'INR',
    vendor: 'JetBrains',
    date: '2026-03-15',
    category: 'business',
    description: 'JetBrains IntelliJ IDEA — monthly subscription',
    isTaxDeductible: true,
    taxType: 'GST',
    taxAmount: 91,
    confidence: 0.93,
    documentType: 'invoice',
    source: 'gmail',
    rawOcrText: 'JetBrains s.r.o.\nInvoice #JB-2026-03\nIntelliJ IDEA Ultimate\nBase ₹508\nGST 18% ₹91\nTotal ₹599',
    aiReasoning: 'IDE subscription from JetBrains. Professional software tool for development work. GST at 18% on software subscriptions. Deductible as business expense under Section 37(1) for professionals.',
    monthYear: '2026-03',
    createdAt: '2026-03-15T12:00:00Z',
    humanReviewed: true,
  },
  {
    id: 'seed-croma-mar',
    amount: 3499,
    currency: 'INR',
    vendor: 'Croma',
    date: '2026-03-20',
    category: 'shopping',
    description: 'Croma — Mechanical keyboard for work',
    isTaxDeductible: true,
    taxType: 'GST',
    taxAmount: 534,
    confidence: 0.85,
    documentType: 'receipt',
    source: 'camera',
    rawOcrText: 'Croma Electronics\nKeychron K2 Wireless Mechanical Keyboard\nBase ₹2,965\nGST 18% ₹534\nTotal ₹3,499',
    aiReasoning: 'Mechanical keyboard purchase from Croma electronics. As a tech professional, this qualifies as work equipment. Deductible under Section 37(1) as professional equipment. Confidence slightly lower as personal use cannot be ruled out.',
    monthYear: '2026-03',
    createdAt: '2026-03-20T14:30:00Z',
    humanReviewed: false,
  },
  {
    id: 'seed-swiggy-mar',
    amount: 389,
    currency: 'INR',
    vendor: 'Swiggy',
    date: '2026-03-08',
    category: 'food',
    description: 'Swiggy order — South Indian thali',
    isTaxDeductible: false,
    taxType: 'GST',
    taxAmount: 19,
    confidence: 0.94,
    documentType: 'upi_screenshot',
    source: 'camera',
    rawOcrText: 'Swiggy\nOrder #SW8372615\nSouth Indian Thali ₹320\nDelivery ₹50\nGST ₹19\nTotal ₹389',
    aiReasoning: 'Food delivery from Swiggy. Personal dining expense. GST at 5% on restaurant services. Not tax deductible.',
    monthYear: '2026-03',
    createdAt: '2026-03-08T13:00:00Z',
    humanReviewed: false,
  },
  {
    id: 'seed-bmtc-mar',
    amount: 55,
    currency: 'INR',
    vendor: 'BMTC',
    date: '2026-03-10',
    category: 'transport',
    description: 'BMTC bus pass — daily ticket',
    isTaxDeductible: false,
    taxType: 'none',
    taxAmount: null,
    confidence: 0.78,
    documentType: 'receipt',
    source: 'camera',
    rawOcrText: 'BMTC\nDaily Pass\nRoute: 500D\n₹55',
    aiReasoning: 'Public transport bus ticket from BMTC (Bangalore Metropolitan Transport Corporation). No GST on public transport. Low confidence due to minimal text on ticket. Personal commute expense.',
    monthYear: '2026-03',
    createdAt: '2026-03-10T07:30:00Z',
    humanReviewed: false,
  },
  {
    id: 'seed-rent-mar',
    amount: 12500,
    currency: 'INR',
    vendor: 'Landlord — Ashok Kumar',
    date: '2026-03-05',
    category: 'rent',
    description: 'Monthly rent — 2BHK Koramangala',
    isTaxDeductible: false,
    taxType: 'none',
    taxAmount: null,
    confidence: 0.88,
    documentType: 'upi_screenshot',
    source: 'camera',
    rawOcrText: 'UPI Payment\nTo: Ashok Kumar\nAmount: ₹12,500\nNote: March rent',
    aiReasoning: 'Monthly rent payment via UPI. Same landlord and amount as previous months. No GST on residential rent. Potential HRA exemption under Section 10(13A).',
    monthYear: '2026-03',
    createdAt: '2026-03-05T09:00:00Z',
    humanReviewed: false,
  },
  {
    id: 'seed-medical-mar',
    amount: 1850,
    currency: 'INR',
    vendor: 'Apollo Pharmacy',
    date: '2026-03-22',
    category: 'medical',
    description: 'Apollo Pharmacy — prescribed medicines',
    isTaxDeductible: true,
    taxType: 'GST',
    taxAmount: 93,
    confidence: 0.86,
    documentType: 'receipt',
    source: 'upload',
    rawOcrText: 'Apollo Pharmacy\nPrescription #AP20260322\nMedicines (various)\nTotal ₹1,850\nGST included',
    aiReasoning: 'Prescription medicines from Apollo Pharmacy. Medical expenses are deductible under Section 80D up to ₹25,000 for self and family. GST at 5% on essential medicines. Marked deductible.',
    monthYear: '2026-03',
    createdAt: '2026-03-22T16:00:00Z',
    humanReviewed: false,
  },
];

export async function seedDatabase(db: import('dexie').Dexie & { transactions: import('dexie').EntityTable<Transaction, 'id'> }) {
  const count = await db.transactions.count();
  if (count === 0) {
    await db.transactions.bulkAdd(seedTransactions);
    return true;
  }
  return false;
}
